version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn test

workflows:
  main:
    jobs:
      - build_and_test
